stages:
  - test
  - deploy

test:
  stage: test
  image: node:22
  script:
    - npm install
    - npm install -D allure-commandline
    - npx wdio run ./wdio.android.app.conf.js || true
    - npx allure generate ./allure-results -o ./allure-report
  artifacts:
    when: always
    paths:
      - allure-results
      - allure-report
    expire_in: 7 days

pages:
  stage: deploy
  dependencies:
    - test
  script:
    - mkdir -p public
    - cp -r allure-report/* public/
  artifacts:
    paths:
      - public
  only:
    - main